### ISSUE TITLE
Using the addon changes the fonts of the application

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/ChipFieldAddon#4]
It seems that adding this addon introduces a change in font size in the application as shown in the following image:

![image](https://user-images.githubusercontent.com/28312758/85203407-025a9580-b2e4-11ea-9084-b7066dc295cc.png)

**Comment by javier-godoy** [comment]
Blocked by #5

**Comment by javier-godoy** [comment]
Confirmed

**Comment by thomasdewaelheyns** [comment]
Is this issue being investigated? Because it is still an issue with the latest version (2.3.0). Which is a shame because it looks really useful.

**Comment by paodb** [comment]
I did some research on this issue and I see that 

`<link rel="stylesheet" type="text/css" crossorigin="anonymous" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic">`

is added because **paper-chip.js**  has an import to **@polymer/paper-styles/paper-styles.js** and this one has an import to **typography.js**. This **typography.js** has an import to **@polymer/font-roboto/roboto.js** and it's this one who adds the <link ....> part cause `window.polymerSkipLoadingFontRoboto` is false:

```javascript
if (!window.polymerSkipLoadingFontRoboto) {
  const link = document.createElement('link');
  link.rel = 'stylesheet';
  link.type = 'text/css';
  link.crossOrigin = 'anonymous';
  link.href =
      'https://fonts.googleapis.com/css?family=Roboto+Mono:400,700|Roboto:400,300,300italic,400italic,500,500italic,700,700italic';
  document.head.appendChild(link);
}
```

According to [this paper-styles issue](https://github.com/PolymerElements/paper-styles/issues/111) one solution will be to set `window.polymerSkipLoadingFontRoboto = true` but I couldn't find the right place to do this within the addon so far. I'll try to come back to this issue as soon as possible.
